### ISSUE TITLE
Edit game fields while uploading multiple games

### ISSUE THREAD

**Issue by mmascher** [Zero-to-Heroes/zerotoheroes.com#22]
Both with arena tracker, and with android (power.log) it is not possible to select a decklist during upload time. This is inconvenient, since you need to go through all the games you are uploading and edit them. I think it would be nice if I could (optionally) select a decklist while uploading them.

On the same line probably selecting a tag for all the games would be good.

And finally, there is the rank thing, which unfortunately is complicated, but I'd love if I could select a starting rank (for the ladder)/starting #wins(for arena) and have zth populate the rank field for me.

I'd say the first 2 may be easy, you might want to spawn a new GH issue for the rank thing if you think it is useful but requires more time.

**Comment by sebastientromp** [comment]
We're trying to move away from manual uploads, so closing it for now. Please don't hesitate to comment on it if it's still needed.

I will try to get in touch once more with ArenaTracker and see if they are open to auto-upload their games as well
