### ISSUE TITLE
On the order game are published with AT replay files

### ISSUE THREAD

**Issue by mmascher** [Zero-to-Heroes/zerotoheroes.com#23]
![schermata 2016-10-13 alle 14 26 07](https://cloud.githubusercontent.com/assets/1586246/19349518/b0954250-9153-11e6-8bc6-973b34be68a3.png)

I tried to upload 14 games from a run I had last night. I expected the games to be sorted in my games from the most recent one, to the less recent one (like with the power.log). Turned out the order is not that.

I also noticed the games are not alphabetically sorted when I select them (see the picture), but then the order in "my games" is different from the one in the creenshot, and yet is different from how they were played.

**Comment by sebastientromp** [comment]
You can upload the games directly from AT since some time ago, so closing this one. Feel free to reopen / comment on it if this is still something you need :)
