### ISSUE TITLE
Add a go-to-draft button when the decklist is from a ZTH draft

### ISSUE THREAD

**Issue by mmascher** [Zero-to-Heroes/zerotoheroes.com#30]
See here http://www.zerotoheroes.com/r/hearthstone/57ff7d6d0ca136458db0cacd/kelthuzad-rulez-2 , AFAICT it is not possible to go from this page to the draft (http://www.zerotoheroes.com/r/hearthstone/57fe85210ca136065e52ed91/12-wins-druid)

**Comment by sebastientromp** [comment]
Indeed, the link from the decklist is broken.
Usually you can do this by middle-clicking on the deck name, but in that case it's broken. Thanks for raising the issue!

**Comment by mmascher** [comment]
No problem, you might also stress in some way when the link is from ZTH, so people know they can go and see the whole draft/thought process that bringed to the deck!

**Comment by sebastientromp** [comment]
Good point! I already do it for HearthArena and ArenaDrafts by adding the site in the deck name, so should be straightforward to extend it to ZetoH
