### ISSUE TITLE
ArenaDrafts deck link has JSON format parameter included

### ISSUE THREAD

**Issue by NobleHelium** [Zero-to-Heroes/zerotoheroes.com#51]
in my last upload http://www.zerotoheroes.com/r/hearthstone/583fa60b196fde07ea7bc1fd/noblehelium-paladin-vs-thugss-shaman-2116-291116
if you click on the deck link, it pops up the decklist at the top
if you click on the deck link there, it sends you to arenadrafts but with the json format parameter appended

**Comment by sebastientromp** [comment]
Change isn't retroactive, but I can fix the deck manually if you need it though
