### ISSUE TITLE
Add support for Blizzard deck export format

### ISSUE THREAD

**Issue by NobleHelium** [Zero-to-Heroes/zerotoheroes.com#95]
I haven't looked closely but I'm guessing the Blizzard deck export format is just a Base 64 encoding of the decklist, so it should be easy to add support for it.

**Comment by sebastientromp** [comment]
It's slightly more complex than that, but it's been implemented already in https://github.com/Zero-to-Heroes/zerotoheroes.com/issues/89 :)
